DROP TABLE HINWEISE if exists;

DROP TABLE Userkurse IF EXISTS
DROP TABLE Kurs IF EXISTS
DROP TABLE TestParam IF EXISTS
DROP TABLE Tests IF EXISTS
DROP TABLE Userlevel IF EXISTS

DROP TABLE Eingaben IF EXISTS
DROP TABLE user IF EXISTS
DROP TABLE Methodenparameter IF EXISTS
DROP TABLE Aufgaben IF EXISTS
DROP TABLE Kategorien IF EXISTS
DROP TABLE Rang IF EXISTS




CREATE TABLE user( 
ID integer GENERATED BY DEFAULT AS IDENTITY,
username VARCHAR(40),
passwort INTEGER,
email VARCHAR(100),
usergruppe VARCHAR(50) DEFAULT 'schueler',
PRIMARY KEY(ID));

CREATE TABLE Rang(
level integer,
rangname VARCHAR(50),
PRIMARY KEY(level));

CREATE TABLE userlevel(
userID integer GENERATED BY DEFAULT AS IDENTITY,
aktLvl integer,
aktExp integer,
PRIMARY KEY(userid),
FOREIGN KEY (userid) REFERENCES user(ID),
FOREIGN KEY (aktLvl) REFERENCES Rang(level));


CREATE TABLE Kategorien(
ID INTEGER GENERATED BY DEFAULT AS IDENTITY,
kategoriename VARCHAR(100),
PRIMARY KEY(id))

CREATE TABLE Aufgaben(
ID INTEGER GENERATED BY DEFAULT AS IDENTITY,
beschreibung VARCHAR(20000),
kategorieID INTEGER,
autor VARCHAR(100),
methodenname VARCHAR(100),
Datentyp VARCHAR(30),
mindestlevel INTEGER,
gegEXP INTEGER,
PRIMARY KEY(id),
FOREIGN KEY (kategorieID) REFERENCES Kategorien(ID),
FOREIGN KEY (mindestlevel) REFERENCES Rang(level));

CREATE TABLE Eingaben(
AufgabenID INTEGER,
UserID INTEGER,
text VARCHAR(20000),
geloest BOOLEAN DEFAULT 'FALSE',
PRIMARY KEY(aufgabenid, userid),
FOREIGN KEY (UserID) REFERENCES user(ID),
FOREIGN KEY (AufgabenID) REFERENCES Aufgaben(ID));


CREATE TABLE MethodenParameter(
aufgabenID Integer,
paraname VARCHAR(30),
Datentyp VARCHAR(30),
PRIMARY KEY(aufgabenID, paraname),
FOREIGN KEY (aufgabenID) REFERENCES Aufgaben(ID));

CREATE TABLE Tests(
AufgabenID INTEGER,
testID INTEGER,
erwtErg VARCHAR(20000),
ergHash INTEGER,
PRIMARY KEY(testID, aufgabenID),
FOREIGN KEY (AufgabenID) REFERENCES Aufgaben(ID));

CREATE TABLE TestParam(
AufgabenID INTEGER,
testID INTEGER,
paraname VARCHAR(200),
typ VARCHAR(200),
wert VARCHAR(20000),
PRIMARY KEY (AufgabenID, testID, paraname),
FOREIGN KEY (paraname, AufgabenID) REFERENCES MethodenParameter(paraname, AufgabenID));

CREATE TABLE Hinweise(
Hinweis VarChar(200) DEFAULT '',
AufgabenID INTEGER,
PRIMARY KEY (Hinweis),
FOREIGN KEY (AufgabenID) REFERENCES Aufgaben(ID)
);

INSERT INTO user VALUES ('0','admin','-529743353','feadare@rbb.do.nw.schule.de','admin');INSERT INTO user VALUES ('1','feaday','935574784','yoshi67@hotmail.de','developer');INSERT INTO user VALUES ('2','taxim11','-34591757','duplo23@yandex.ru','schueler');INSERT INTO user VALUES ('3','blackbreed','1178330124','noo@troll.xdd','schueler');INSERT INTO user VALUES ('4','polo','-1795388216','g.palamito@gmx.de','schueler');INSERT INTO user VALUES ('5','dupl23','-1082793596','d@d.de','schueler');INSERT INTO user VALUES ('6','duplo232','1050164195','d@d.de','schueler');INSERT INTO user VALUES ('7','LOLnubs','98701968','schiggy69@gmail.com','schueler');INSERT INTO user VALUES ('8','kek','2144986682','Birne_Mango@hotmail.de','schueler');INSERT INTO user VALUES ('9','dasidjai','1428737386','alles@klar.de','schueler');INSERT INTO user VALUES ('10','dasdsadsadasd','-1931364217','Jo@jo.jo','schueler');INSERT INTO user VALUES ('11','de','583346353','d@d.de','schueler');
INSERT INTO Rang VALUES ('0', 'Admi(n)ral');
INSERT INTO Rang VALUES ('1', 'Neuling');

INSERT INTO Rang VALUES ('2', 'Copy-Pasteter');

INSERT INTO Rang VALUES ('3', 'Neuling Abstract Class');

INSERT INTO Rang VALUES ('4', 'Neuling First Class');

INSERT INTO Rang VALUES ('5', 'Lehrling I');

INSERT INTO Rang VALUES ('6', 'Lehrling II');

INSERT INTO Rang VALUES ('7', 'Lehrling III');

INSERT INTO Rang VALUES ('8', 'Lehrling IIII');

INSERT INTO Rang VALUES ('9', 'Wichtel Code');

INSERT INTO Rang VALUES ('10', 'Variabel Fee');

INSERT INTO Rang VALUES ('11', 'Klassen Raider');

INSERT INTO Rang VALUES ('12', 'Quellcode Prädiger');

INSERT INTO Rang VALUES ('13', 'Code Beschwörer' );

INSERT INTO Rang VALUES ('14', 'Bit Priester');

INSERT INTO Rang VALUES ('15', 'Error Schamane');

INSERT INTO Rang VALUES ('16', 'Dunkler Coder');

INSERT INTO Rang VALUES ('17', 'JavAkrobat');

INSERT INTO Rang VALUES ('18', 'Daten Jongleur');

INSERT INTO Rang VALUES ('19', 'Konstruktor');

INSERT INTO Rang VALUES ('20', 'Mächtiger Java Meister');

INSERT INTO Rang VALUES ('21', 'Überlegener Server Admin');

INSERT INTO Rang VALUES ('22', 'Programier Naturtalent');

INSERT INTO Rang VALUES ('23', 'Übermenschlicher Coder');

INSERT INTO Rang VALUES ('24', '0101011101100101011100110110010101101110');

INSERT INTO Rang VALUES ('25', 'Binäres Wesen');

INSERT INTO Rang VALUES ('26', 'Infernaler Daten Dämon');

INSERT INTO Rang VALUES ('27', 'Lucifer des Codes');

INSERT INTO Rang VALUES ('28', 'Heiliger Code Engel');

INSERT INTO Rang VALUES ('29', 'Erz-Engel des Programierens');

INSERT INTO Rang VALUES ('30', 'Programmier Gottheit');INSERT INTO userlevel VALUES ('1','20','62');INSERT INTO userlevel VALUES ('2','1','5');INSERT INTO userlevel VALUES ('3','2','45');INSERT INTO userlevel VALUES ('4','3','0');INSERT INTO userlevel VALUES ('5','1','20');INSERT INTO userlevel VALUES ('6','1','0');INSERT INTO userlevel VALUES ('7','1','0');INSERT INTO userlevel VALUES ('8','1','0');INSERT INTO userlevel VALUES ('9','1','0');INSERT INTO userlevel VALUES ('10','1','0');INSERT INTO userlevel VALUES ('11','1','0');
INSERT INTO Kategorien VALUES ('1', 'Basics');INSERT INTO Kategorien VALUES ('2', 'Fallunterscheidungen');

INSERT INTO Kategorien VALUES ('3', 'Schleifen');

INSERT INTO Kategorien VALUES ('4', 'Strings');

INSERT INTO Kategorien VALUES ('5', 'Logik');

INSERT INTO Kategorien VALUES ('6', 'Zahlen');

INSERT INTO Kategorien VALUES ('7', 'Arrays');

INSERT INTO Kategorien VALUES ('8', 'Felder');

INSERT INTO Kategorien VALUES ('9', 'Fortgeschrittene');

INSERT INTO Kategorien VALUES ('10', 'Andere');
INSERT INTO Aufgaben VALUES ('2','BegrÃŒÃ?e die Welt! 
Gebe einfach einen String zurÃŒck der die aktuelle Welt begrÃŒÃ?t!
halloWelt("Erde") -> "Hallo Erde!"','1','feaday','halloWelt','String','1','5');INSERT INTO Aufgaben VALUES ('3','Addiere zahl1 mit zahl2, vorher musst du diese in Integers umwandeln!','6','blackbreed','parseZahlen','Integer','5','25');INSERT INTO Aufgaben VALUES ('4','Gebe den Namen und das Alter einer Person in folgender Form aus: "Name: Maxim; Alter: 18; Beruf: Bugtester"
personenBeschreibung("Polo", 18, "pololos")-> "Name: polo, Alter: 18, Beruf: pololos"','1','feaday','personenBeschreibung','String','2','8');INSERT INTO Aufgaben VALUES ('5','Vergleiche mithilfe einer If-Anweisung die Strings. 
ZusÃ€tzlich soll false zurÃŒck gegeben werden, falls einer der Strings null ist.','2','blackbreed','vergleicheStrings','Boolean','2','15');INSERT INTO Aufgaben VALUES ('8','Addiere zu dem String wort den String extra und zwar so oft wie der Integer anzahl ist!','3','blackbreed','addiereWort','String','5','20');INSERT INTO Aufgaben VALUES ('10','Hier haben wir eine Subtraktionsaufgabe in der a von b und das dan von c abgezogen wird.','1','polo','einfacheSubtraktion','Integer','1','10');INSERT INTO Aufgaben VALUES ('11','Multipliziere die Variablen a, b & c.','1','polo','einfacheMultiplikation','Integer','1','10');INSERT INTO Aufgaben VALUES ('12','Teile a durch b;','1','polo','einfacheDivision','Integer','1','10');INSERT INTO Aufgaben VALUES ('13','Teile a durch b, addiere dies mit c geteillt durch d und subtrahiere dann dies mit e durch f.','6','polo','seriosMath','Integer','5','50');INSERT INTO Aufgaben VALUES ('18','PrÃ¼fe das Geschlecht einer Person. Wenn x true ist, ist die Person Weiblich, bei false ist sie MÃ¤nnlich. Gaben sie "Herr/Frau" + nachname zurÃ¼ck.
isWeiblich(true, Baum) --> "Frau Baum"','2','polo','isWeiblich','String','1','20');INSERT INTO Aufgaben VALUES ('20','Umschliesse String x mit dem String tag;
tag(Wald, Baum); --> WaldBaumWald','4','polo','tag','String','1','10');INSERT INTO Aufgaben VALUES ('24','Fuege String a und b zusammen und ermittle die laenge der Zeichenkette. Benutze dafuer String.length(). countString("Guten", "Tag") --> 8; ','4','polo','countStrings','Integer','1','101');INSERT INTO Aufgaben VALUES ('25','Geralt von Riva moechte sich neue Schwerter kaufen.
Allerdings weiss er nicht ob sein Geld reicht.
Hilf ihm dabei! 

Pruefe ob sein Geld aufTasche genuegend ist fÃ¼r die kosten.','5','dupl23','enoughMoney','Boolean','1','10');INSERT INTO Aufgaben VALUES ('26','Damit kleine Kinder nachts besser schlafen koennen und morgends puenklich aus dem Bett kommen duerfen sie ab gewissen Uhrzeiten keine Cola mehr trinken und kein SueÃkram mehr essen.<br> Kinder von 0-3 duerfen keine Cola aber bis 16 Uhr Suessigkeiten essen.<br> Von 4-8 duerfen sie bis 18 Uhr Cola und bis 19 Uhr Suesskram.<br> Von 9 bis 12 duerfen sie beides bis 20 Uhr.<br> von 13 bis 17 duerfen sie beides bis 22 Uhr und<br> ab 18 duerfen sie immer beides haben.<br> (Suesskram wird ab 12 Uhr Mittags ausgeteilt)<br>
darfZucker(9, 19.33, true, true); --> true','5','polo','darfZucker','Boolean','10','123');INSERT INTO Aufgaben VALUES ('27','Damit kleine Kinder nachts besser schlafen koennen und morgends puenklich aus dem Bett kommen duerfen sie ab gewissen Uhrzeiten keine Cola mehr trinken und kein SueÃkram mehr essen.<br> Kinder von 0-3 duerfen keine Cola aber bis 16 Uhr Suessigkeiten essen.<br> Von 4-8 duerfen sie bis 18 Uhr Cola und bis 19 Uhr Suesskram.<br> Von 9 bis 12 duerfen sie beides bis 20 Uhr.<br> von 13 bis 17 duerfen sie beides bis 22 Uhr und<br> ab 18 duerfen sie immer beides haben.<br> (Suesskram wird ab 12 Uhr Mittags ausgeteilt)<br>
darfZucker(9, 19.33, true, true); --> true','5','polo','darfZucker','Boolean','10','123');
INSERT INTO Eingaben VALUES ('2','1','return "Hallo "+world+"!";','true');INSERT INTO Eingaben VALUES ('2','3','return "Hallo "+world+"!";','true');INSERT INTO Eingaben VALUES ('2','5','return "df<br>asdasd"+world;','false');INSERT INTO Eingaben VALUES ('3','3','int kek = 0;
 int wow = 0;
        kek = Integer.parseInt(zahl1);
        wow = Integer.parseInt(zahl2);
        int result = kek+wow;
        return result;','true');INSERT INTO Eingaben VALUES ('4','1','return "Name: "+name+", Alter: 18"+", Beruf: "+beruf;','true');INSERT INTO Eingaben VALUES ('5','1','return a.equals(b);','true');INSERT INTO Eingaben VALUES ('5','3','   boolean result = false;
        if(a == null || a == ""){  
            return result;
        }
        if(a==b){
            result = true;
        }
        return result;
','true');INSERT INTO Eingaben VALUES ('13','4','return 1;','false');INSERT INTO Eingaben VALUES ('20','5','return tag+x+tag;','true');INSERT INTO Eingaben VALUES ('24','4','return a.length() + b.length();','true');INSERT INTO Eingaben VALUES ('25','5','if(kosten<=aufTasche){
 return true;
}
else{
 return false;
}','true');
INSERT INTO Methodenparameter VALUES ('2','world','String');INSERT INTO Methodenparameter VALUES ('3','zahl1','String');INSERT INTO Methodenparameter VALUES ('3','zahl2','String');INSERT INTO Methodenparameter VALUES ('4','alter','Integer');INSERT INTO Methodenparameter VALUES ('4','beruf','String');INSERT INTO Methodenparameter VALUES ('4','name','String');INSERT INTO Methodenparameter VALUES ('5','a','String');INSERT INTO Methodenparameter VALUES ('5','b','String');INSERT INTO Methodenparameter VALUES ('8','anzahl','Integer');INSERT INTO Methodenparameter VALUES ('8','extra','String');INSERT INTO Methodenparameter VALUES ('8','wort','String');INSERT INTO Methodenparameter VALUES ('10','a','Integer');INSERT INTO Methodenparameter VALUES ('10','b','Integer');INSERT INTO Methodenparameter VALUES ('10','c','Integer');INSERT INTO Methodenparameter VALUES ('11','a','Integer');INSERT INTO Methodenparameter VALUES ('11','b','Integer');INSERT INTO Methodenparameter VALUES ('11','c','Integer');INSERT INTO Methodenparameter VALUES ('12','a','Integer');INSERT INTO Methodenparameter VALUES ('12','b','Integer');INSERT INTO Methodenparameter VALUES ('13','a','Integer');INSERT INTO Methodenparameter VALUES ('13','b','Integer');INSERT INTO Methodenparameter VALUES ('13','c','Integer');INSERT INTO Methodenparameter VALUES ('13','d','Integer');INSERT INTO Methodenparameter VALUES ('13','e','Integer');INSERT INTO Methodenparameter VALUES ('13','f','Integer');INSERT INTO Methodenparameter VALUES ('18','nachname','String');INSERT INTO Methodenparameter VALUES ('18','x','Boolean');INSERT INTO Methodenparameter VALUES ('20','tag','String');INSERT INTO Methodenparameter VALUES ('20','x','String');INSERT INTO Methodenparameter VALUES ('24','a','String');INSERT INTO Methodenparameter VALUES ('24','b','String');INSERT INTO Methodenparameter VALUES ('25','aufTasche','Integer');INSERT INTO Methodenparameter VALUES ('25','kosten','Integer');INSERT INTO Methodenparameter VALUES ('26','alter','Integer');INSERT INTO Methodenparameter VALUES ('26','uhrzeit','Double');INSERT INTO Methodenparameter VALUES ('26','willCola','Boolean');INSERT INTO Methodenparameter VALUES ('27','alter','Integer');INSERT INTO Methodenparameter VALUES ('27','uhrzeit','Double');INSERT INTO Methodenparameter VALUES ('27','willCola','Boolean');INSERT INTO Methodenparameter VALUES ('27','willSuesskram','Boolean');
INSERT INTO Tests VALUES ('2','1','Hallo Erde!','-93038999');INSERT INTO Tests VALUES ('3','1','10','1567');INSERT INTO Tests VALUES ('4','1','Name: Hendrik, Alter: 18, Beruf: Drogendealer','-1795376517');INSERT INTO Tests VALUES ('5','1','false','97196323');INSERT INTO Tests VALUES ('8','1','hioPoPoPoPoPoP','153800263');INSERT INTO Tests VALUES ('10','1','0','48');INSERT INTO Tests VALUES ('11','1','408','51516');INSERT INTO Tests VALUES ('12','1','2','50');INSERT INTO Tests VALUES ('13','1','10','1567');INSERT INTO Tests VALUES ('18','1','Frau Baum','-1581107913');INSERT INTO Tests VALUES ('20','1','WaldBaumWald','-1562898053');INSERT INTO Tests VALUES ('24','1','9','57');INSERT INTO Tests VALUES ('25','1','true','3569038');INSERT INTO Tests VALUES ('26','1','FRESHDUMMYDORE','0');INSERT INTO Tests VALUES ('27','1','true','3569038');INSERT INTO Tests VALUES ('2','2','Hallo Mars!','-86143390');INSERT INTO Tests VALUES ('3','2','14','1571');INSERT INTO Tests VALUES ('4','2','Name: Dieter, Alter: 9, Beruf: Admin','-370091552');INSERT INTO Tests VALUES ('5','2','true','3569038');INSERT INTO Tests VALUES ('8','2','KebabKeKKeKKeK','-1753839224');INSERT INTO Tests VALUES ('10','2','22','1600');INSERT INTO Tests VALUES ('11','2','666','53622');INSERT INTO Tests VALUES ('12','2','8','56');INSERT INTO Tests VALUES ('13','2','74','1757');INSERT INTO Tests VALUES ('18','2','Herr Wald','34651141');INSERT INTO Tests VALUES ('20','2','"Zweiundvierzig"','34312402');INSERT INTO Tests VALUES ('24','2','38','1637');INSERT INTO Tests VALUES ('25','2','false','97196323');INSERT INTO Tests VALUES ('2','3','Hallo Netherworld!','171512305');INSERT INTO Tests VALUES ('3','3','30','1629');INSERT INTO Tests VALUES ('5','3','false','97196323');INSERT INTO Tests VALUES ('8','3','Wald besteht aus BaumBaumBaumBaumBaumBaumBaumBaumBaumBaumBaumBaum','-1181177146');INSERT INTO Tests VALUES ('10','3','123','48690');INSERT INTO Tests VALUES ('11','3','420','51570');INSERT INTO Tests VALUES ('12','3','6','54');INSERT INTO Tests VALUES ('13','3','3','51');INSERT INTO Tests VALUES ('18','3','Frau Baum-Wald','-120283976');INSERT INTO Tests VALUES ('20','3','/\/','48066');INSERT INTO Tests VALUES ('24','3','159','48789');INSERT INTO Tests VALUES ('25','3','true','3569038');INSERT INTO Tests VALUES ('2','4','Hallo Sylverant!','-2001561855');INSERT INTO Tests VALUES ('24','4','8','56');INSERT INTO Tests VALUES ('2','5','Hallo Zanarkand!','-554295865');
INSERT INTO TestParam VALUES ('2','1','world','String','Erde');INSERT INTO TestParam VALUES ('2','2','world','String','Mars');INSERT INTO TestParam VALUES ('2','3','world','String','Netherworld');INSERT INTO TestParam VALUES ('2','4','world','String','Sylverant');INSERT INTO TestParam VALUES ('2','5','world','String','Zanarkand');INSERT INTO TestParam VALUES ('3','1','zahl1','String','3');INSERT INTO TestParam VALUES ('3','1','zahl2','String','7');INSERT INTO TestParam VALUES ('3','2','zahl1','String','11');INSERT INTO TestParam VALUES ('3','2','zahl2','String','3');INSERT INTO TestParam VALUES ('3','3','zahl1','String','9');INSERT INTO TestParam VALUES ('3','3','zahl2','String','21');INSERT INTO TestParam VALUES ('4','1','alter','Integer','18');INSERT INTO TestParam VALUES ('4','1','beruf','String','Drogendealer');INSERT INTO TestParam VALUES ('4','1','name','String','Hendrik');INSERT INTO TestParam VALUES ('4','2','alter','Integer','9');INSERT INTO TestParam VALUES ('4','2','beruf','String','Admin');INSERT INTO TestParam VALUES ('4','2','name','String','Dieter');INSERT INTO TestParam VALUES ('5','1','a','String','b');INSERT INTO TestParam VALUES ('5','1','b','String','a');INSERT INTO TestParam VALUES ('5','2','a','String','a');INSERT INTO TestParam VALUES ('5','2','b','String','a');INSERT INTO TestParam VALUES ('5','3','a','String','b');INSERT INTO TestParam VALUES ('5','3','b','String',' ');INSERT INTO TestParam VALUES ('8','1','anzahl','Integer','6');INSERT INTO TestParam VALUES ('8','1','extra','String','oP');INSERT INTO TestParam VALUES ('8','1','wort','String','hi');INSERT INTO TestParam VALUES ('8','2','anzahl','Integer','3');INSERT INTO TestParam VALUES ('8','2','extra','String','KeK');INSERT INTO TestParam VALUES ('8','2','wort','String','Kebab');INSERT INTO TestParam VALUES ('8','3','anzahl','Integer','12');INSERT INTO TestParam VALUES ('8','3','extra','String','Baum');INSERT INTO TestParam VALUES ('8','3','wort','String','Wald besteht aus ');INSERT INTO TestParam VALUES ('10','1','a','Integer','3');INSERT INTO TestParam VALUES ('10','1','b','Integer','2');INSERT INTO TestParam VALUES ('10','1','c','Integer','1');INSERT INTO TestParam VALUES ('10','2','a','Integer','42');INSERT INTO TestParam VALUES ('10','2','b','Integer','13');INSERT INTO TestParam VALUES ('10','2','c','Integer','7');INSERT INTO TestParam VALUES ('10','3','a','Integer','666');INSERT INTO TestParam VALUES ('10','3','b','Integer','420');INSERT INTO TestParam VALUES ('10','3','c','Integer','123');INSERT INTO TestParam VALUES ('11','1','a','Integer','12');INSERT INTO TestParam VALUES ('11','1','b','Integer','34');INSERT INTO TestParam VALUES ('11','1','c','Integer','1');INSERT INTO TestParam VALUES ('11','2','a','Integer','111');INSERT INTO TestParam VALUES ('11','2','b','Integer','2');INSERT INTO TestParam VALUES ('11','2','c','Integer','3');INSERT INTO TestParam VALUES ('11','3','a','Integer','6');INSERT INTO TestParam VALUES ('11','3','b','Integer','7');INSERT INTO TestParam VALUES ('11','3','c','Integer','10');INSERT INTO TestParam VALUES ('12','1','a','Integer','14');INSERT INTO TestParam VALUES ('12','1','b','Integer','7');INSERT INTO TestParam VALUES ('12','2','a','Integer','288');INSERT INTO TestParam VALUES ('12','2','b','Integer','36');INSERT INTO TestParam VALUES ('12','3','a','Integer','54');INSERT INTO TestParam VALUES ('12','3','b','Integer','9');INSERT INTO TestParam VALUES ('13','1','a','Integer','4');INSERT INTO TestParam VALUES ('13','1','b','Integer','2');INSERT INTO TestParam VALUES ('13','1','c','Integer','44');INSERT INTO TestParam VALUES ('13','1','d','Integer','4');INSERT INTO TestParam VALUES ('13','1','e','Integer','21');INSERT INTO TestParam VALUES ('13','1','f','Integer','7');INSERT INTO TestParam VALUES ('13','2','a','Integer','0');INSERT INTO TestParam VALUES ('13','2','b','Integer','12345');INSERT INTO TestParam VALUES ('13','2','c','Integer','123');INSERT INTO TestParam VALUES ('13','2','d','Integer','1');INSERT INTO TestParam VALUES ('13','2','e','Integer','245');INSERT INTO TestParam VALUES ('13','2','f','Integer','5');INSERT INTO TestParam VALUES ('13','3','a','Integer','9');INSERT INTO TestParam VALUES ('13','3','b','Integer','3');INSERT INTO TestParam VALUES ('13','3','c','Integer','12');INSERT INTO TestParam VALUES ('13','3','d','Integer','4');INSERT INTO TestParam VALUES ('13','3','e','Integer','15');INSERT INTO TestParam VALUES ('13','3','f','Integer','5');INSERT INTO TestParam VALUES ('18','1','nachname','String','Baum');INSERT INTO TestParam VALUES ('18','1','x','Boolean','true');INSERT INTO TestParam VALUES ('18','2','nachname','String','Wald');INSERT INTO TestParam VALUES ('18','2','x','Boolean','false');INSERT INTO TestParam VALUES ('18','3','nachname','String','Baum-Wald');INSERT INTO TestParam VALUES ('18','3','x','Boolean','true');INSERT INTO TestParam VALUES ('20','1','tag','String','Wald');INSERT INTO TestParam VALUES ('20','1','x','String','Baum');INSERT INTO TestParam VALUES ('20','2','tag','String','"');INSERT INTO TestParam VALUES ('20','2','x','String','Zweiundvierzig');INSERT INTO TestParam VALUES ('20','3','tag','String','/');INSERT INTO TestParam VALUES ('20','3','x','String','\');INSERT INTO TestParam VALUES ('24','1','a','String','Hallo');INSERT INTO TestParam VALUES ('24','1','b','String','Welt');INSERT INTO TestParam VALUES ('24','2','a','String','Superkalifragilistischexpialigetisch');INSERT INTO TestParam VALUES ('24','2','b','String','xd');INSERT INTO TestParam VALUES ('24','3','a','String','lolololololololololololololololololololololololololololololololololololololololololololololololol');INSERT INTO TestParam VALUES ('24','3','b','String','woooooooooooooooooooooooooooooooooooooooooooooooooooooooooooow');INSERT INTO TestParam VALUES ('24','4','a','String','Guten');INSERT INTO TestParam VALUES ('24','4','b','String','Tag');INSERT INTO TestParam VALUES ('25','1','aufTasche','Integer','100');INSERT INTO TestParam VALUES ('25','1','kosten','Integer','50');INSERT INTO TestParam VALUES ('25','2','aufTasche','Integer','300');INSERT INTO TestParam VALUES ('25','2','kosten','Integer','420');INSERT INTO TestParam VALUES ('25','3','aufTasche','Integer','200');INSERT INTO TestParam VALUES ('25','3','kosten','Integer','200');INSERT INTO TestParam VALUES ('26','1','alter','Integer','FRESHDUMMYDORE');INSERT INTO TestParam VALUES ('26','1','uhrzeit','Double','FRESHDUMMYDORE');INSERT INTO TestParam VALUES ('26','1','willCola','Boolean','FRESHDUMMYDORE');INSERT INTO TestParam VALUES ('27','1','alter','Integer','3');INSERT INTO TestParam VALUES ('27','1','uhrzeit','Double','15.55');INSERT INTO TestParam VALUES ('27','1','willCola','Boolean','false');INSERT INTO TestParam VALUES ('27','1','willSuesskram','Boolean','true');
